### ISSUE TITLE
divide by zero encountered in log

### ISSUE THREAD

**Issue by jaavedm** [npdeloss/meirlop#2]
Hello,

I'm running into an issue with Merilop. My input FASTA file has 3260 sequences and I'm encountering a divide by zero error. I've confirmed that the software runs to completion, sans errors, on the provided input FASTA file called "deseq2-ifnb.diff-peaks.scored.fa". 

Can you help me understand what I'm doing incorrectly. 

Thanks

COMMAND:
`meirlop --fa input.fa --jobs 12 --scan --html --svg JASPAR2020_CORE_vertebrates_non-redundant_pfms_jaspar.txt JASPAR2020_CORE_vertebrates_non-redundant_pfms`

OUTPUT:
```
importing peak data
2021-07-18 00:28:13.354052
0.08911053295014426 seconds
2021-07-18 00:28:13.443156
scanning for motifs
...
11.591122789948713 seconds
2021-07-18 00:28:24.945206
calculating kmer frequency ratios
100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 3214/3214 [00:00<00:00, 4434.90it/s]
frequency_ratio_df_shape = (3214, 16)
frequency_ratio_df_columns = Index(['peak_id', 'kmer_ratio_AA', 'kmer_ratio_AC', 'kmer_ratio_AG',
       'kmer_ratio_AT', 'kmer_ratio_CA', 'kmer_ratio_CC', 'kmer_ratio_CG',
       'kmer_ratio_CT', 'kmer_ratio_GA', 'kmer_ratio_GC', 'kmer_ratio_GG',
       'kmer_ratio_GT', 'kmer_ratio_TA', 'kmer_ratio_TC', 'kmer_ratio_TG'],
      dtype='object')
number of covariates dfs used:
1
12.811943944951054 seconds
2021-07-18 00:28:26.166005
performing logistic regression
Reduced covariates to 11 principal components
Components were chosen to explain 99.0% of variance in covariates
 47%|███████████████████████████████████████████████▌                                                     | 346/735 [00:06<00:08, 47.44it/s]/home/jaavedm/.local/lib/python3.7/site-packages/statsmodels/discrete/discrete_model.py:1747: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/home/jaavedm/.local/lib/python3.7/site-packages/statsmodels/discrete/discrete_model.py:1800: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))
Traceback (most recent call last):
  File "/data1/jaavedm/packages/anaconda3/envs/my_env/bin/meirlop", line 11, in <module>
    sys.exit(main())
  File "/data1/jaavedm/packages/anaconda3/envs/my_env/lib/python3.7/site-packages/meirlop/__main__.py", line 27, in main
    args.func(args)
  File "/data1/jaavedm/packages/anaconda3/envs/my_env/lib/python3.7/site-packages/meirlop/__main__.py", line 328, in run_meirlop
    revcomp = revcomp)
  File "/data1/jaavedm/packages/anaconda3/envs/my_env/lib/python3.7/site-packages/meirlop/motif_enrichment.py", line 200, in analyze_scored_fasta_data_with_lr
    progress_wrapper = tqdm)
  File "/data1/jaavedm/packages/anaconda3/envs/my_env/lib/python3.7/site-packages/meirlop/motif_enrichment.py", line 248, in analyze_peaks_with_lr
    in progress_wrapper(valid_peak_ids)]
  File "/data1/jaavedm/packages/anaconda3/envs/my_env/lib/python3.7/site-packages/meirlop/motif_enrichment.py", line 247, in <listcomp>
    for motif_id
  File "/data1/jaavedm/packages/anaconda3/envs/my_env/lib/python3.7/site-packages/meirlop/motif_enrichment.py", line 238, in process_motif_id
    cov_colnames)[:-1])
  File "/data1/jaavedm/packages/anaconda3/envs/my_env/lib/python3.7/site-packages/meirlop/motif_enrichment.py", line 333, in compute_logit_regression_for_peak_set
    result = model.fit(disp=0)
  File "/home/jaavedm/.local/lib/python3.7/site-packages/statsmodels/discrete/discrete_model.py", line 1913, in fit
    disp=disp, callback=callback, **kwargs)
  File "/home/jaavedm/.local/lib/python3.7/site-packages/statsmodels/discrete/discrete_model.py", line 216, in fit
    disp=disp, callback=callback, **kwargs)
  File "/home/jaavedm/.local/lib/python3.7/site-packages/statsmodels/base/model.py", line 533, in fit
    Hinv = np.linalg.inv(-retvals['Hessian']) / nobs
  File "<__array_function__ internals>", line 6, in inv
  File "/home/jaavedm/.local/lib/python3.7/site-packages/numpy/linalg/linalg.py", line 547, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
  File "/home/jaavedm/.local/lib/python3.7/site-packages/numpy/linalg/linalg.py", line 97, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.LinAlgError: Singular matrix
 47%|███████████████████████████████████████████████▊                                                     | 348/735 [00:07<00:08, 46.53it/s]
```

**Comment by jaavedm** [comment]
Hello, Any ideas on how to troubleshoot this error message. I can send along an input file for you to reproduce the error.

**Comment by npdeloss** [comment]
Hi Jaave,
Thanks for bringing this to my attention. What does the distribution of scores in the input file look like?
