### ISSUE TITLE
scored bed file format

### ISSUE THREAD

**Issue by hsriniva11** [npdeloss/meirlop#3]
Hi,
This is a sample of my scored bed file

`
chr12	97061051	97062237	merged_10	-0.245689838393023	.
chr2	57629190	57630191	merged_100	-0.157350109304036	.
chr6	100838637	100839876	merged_1000	4.78625104090801	.
`

This is the error I get. Not sure what I'm doing wrong here. The bed file is 6 columns with the last 2 being score and score and strand

`
importing peak data
2021-08-18 18:17:54.689990
Traceback (most recent call last):
  File "/broad/rosenlab_archive/Software/meirlop-0.0.16/miniconda3/envs/myenv/bin/meirlop", line 11, in <module>
    sys.exit(main())
  File "/broad/rosenlab_archive/Software/meirlop-0.0.16/miniconda3/envs/myenv/lib/python3.7/site-packages/meirlop/__main__.py", line 27, in main
    args.func(args)
  File "/broad/rosenlab_archive/Software/meirlop-0.0.16/miniconda3/envs/myenv/lib/python3.7/site-packages/meirlop/__main__.py", line 328, in run_meirlop
    revcomp = revcomp)
  File "/broad/rosenlab_archive/Software/meirlop-0.0.16/miniconda3/envs/myenv/lib/python3.7/site-packages/meirlop/motif_enrichment.py", line 55, in analyze_scored_fasta_data_with_lr
    in peak_sequence_dict.keys()}
  File "/broad/rosenlab_archive/Software/meirlop-0.0.16/miniconda3/envs/myenv/lib/python3.7/site-packages/meirlop/motif_enrichment.py", line 54, in <dictcomp>
    for sequence_id 
KeyError: 'merged_10::chr12:97061051-97062237'
`

**Comment by hsriniva11** [comment]
I tried to run using a Fasta file instead of a bed file. I get similar error

`
importing peak data
2021-08-20 17:53:38.874099
Traceback (most recent call last):
  File "/broad/rosenlab_archive/Software/meirlop-0.0.16/miniconda3/envs/myenv/bin/meirlop", line 11, in <module>
    sys.exit(main())
  File "/broad/rosenlab_archive/Software/meirlop-0.0.16/miniconda3/envs/myenv/lib/python3.7/site-packages/meirlop/__main__.py", line 27, in main
    args.func(args)
  File "/broad/rosenlab_archive/Software/meirlop-0.0.16/miniconda3/envs/myenv/lib/python3.7/site-packages/meirlop/__main__.py", line 328, in run_meirlop
    revcomp = revcomp)
  File "/broad/rosenlab_archive/Software/meirlop-0.0.16/miniconda3/envs/myenv/lib/python3.7/site-packages/meirlop/motif_enrichment.py", line 55, in analyze_scored_fasta_data_with_lr
    in peak_sequence_dict.keys()}
  File "/broad/rosenlab_archive/Software/meirlop-0.0.16/miniconda3/envs/myenv/lib/python3.7/site-packages/meirlop/motif_enrichment.py", line 54, in <dictcomp>
    for sequence_id 
KeyError: 'chr12:97061451-97061837'
`

**Comment by hsriniva11** [comment]
Used nameOnly option to get the Fasta file and scored the bed through the covariates. Worked out fine.
